# When editing the contents of this file, TestEntitiesToml may need to be updated

[phone]
"en-AU" = ["0487439000", "+61487439000", "0487 439 000"]

[name]
"en-AU" = ["John Richards", "Danielle Wong"]

[IPAddress]
"en-AU" = ["47.124.160.94", "135.34.220.4"]
